#' Create review templates.
#'
#' Creates skeleton review files:
#' \itemize{
#' \item `index.Rmd`: `html_notebook` to perform and record review in
#' \item `README.md`: prepopulated README for review repo.
#' }
#' `index.Rmd` will be automatically added to `.Rbuildignore`. The resulting templates are populated with default
#' YAML frontmatter and R fenced code chunks (`Rmd`).
#'
#' @param pkg_data package metadata generated by pkgreview_getdata()
#'
#' @export
# @importFrom usethis getFromNamespace check_installed
# @importFrom usethis getFromNamespace render_template
#' @examples
#' \dontrun{
#' pkg_data <- pkgreview_getdata(pkg_dir)
#' pkgreview_index_rmd(pkg_data)
#' pkgreview_readme_md(pkg_data)
#' }
pkgreview_index_rmd <- function(pkg_data) {
    usethis:::check_installed("rmarkdown")

    usethis::use_template(
        "review-index",
        "index.Rmd",
        data = pkg_data,
        ignore = FALSE,
        open = FALSE,
        package = "pkgreviewr"
    )

    if (usethis:::uses_git()) {
        usethis::use_git_hook(
            "pre-commit",
            usethis:::render_template("readme-rmd-pre-commit.sh",
                                      package = "pkgreviewr")
        )
    }

    invisible(TRUE)
}

#' @export
#' @rdname pkgreview_index_rmd
pkgreview_readme_md <- function(pkg_data) {

    usethis::use_template(
        "review-README",
        "README.md",
        data = pkg_data,
        ignore = FALSE,
        open = FALSE,
        package = "pkgreviewr"
    )
}

#' Create review sumbission
#'
#' Clone an up to date ropensci onboarding review template.
#' @return writes a `pkgreview.md` template submission file in the review project root.
#' @export
#'
#' @examples
#' \dontrun{
#' use_reviewtmpl()
#' }
use_reviewtmpl <- function(){
    review_txt <- gh::gh("/repos/:owner/:repo/contents/:path",
                         owner = "ropensci",
                         repo = "onboarding",
                         path = "reviewer_template.md")

    review_txt <- review_txt$content
    review_txt <- rawToChar(base64enc::base64decode(review_txt))

    new <- usethis:::write_over(usethis::proj_get(), "pkgreview.md", review_txt)
    #if(open){
    #    usethis:::edit_file(usethis::proj_get(), "pkgreview.md")
    #}
    invisible(new)
}
